version: '3.9'

services:
  bot:
    container_name: "${PROJECT_NAME}-bot"
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: ../.
      dockerfile: ./docker/Dockerfile
    networks:
      - network
    expose:
      - "4000"
    depends_on:
      - db

  db:
    container_name: "${PROJECT_NAME}-db"
    image: postgres:13-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres-storage:/var/lib/postgresql/data
      - ../init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    networks:
      - network
    command: -p ${POSTGRES_PORT:-5432}

volumes:
  postgres-storage:
    name: "${PROJECT_NAME}-db"

networks:
  network:
    name: network
